### ISSUE TITLE
Fatal Error: 110 OpenTelemetry PHP OTLP Exporter

### ISSUE THREAD

**Issue by erickneverson** [Aternity/Tech-Community#30]
Fatal Error received for getTracer function:

https://github.com/Aternity/Tech-Community/blob/b47e106c57e0355bbd39a2c392acfa47dee4d3f0/110-opentelemetry-php-app/src/SampleOTLPhttpExporter.php#L40

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function OpenTelemetry\SDK\Trace\TracerProvider::getTracer(), 0 passed in /var/www/html/SampleOTLPhttpExporter.php on line 40 and at least 1 expected in /var/www/html/vendor/open-telemetry/opentelemetry/src/SDK/Trace/TracerProvider.php:61 Stack trace: #0 /var/www/html/SampleOTLPhttpExporter.php(40): OpenTelemetry\SDK\Trace\TracerProvider->getTracer() #1 {main} thrown in /var/www/html/vendor/open-telemetry/opentelemetry/src/SDK/Trace/TracerProvider.php on line 61

Will any string value suffice?

**Comment by gwenblum** [comment]
Definitely, let's fix this in both SampleOTLPhttpExporter.php and SampleZipkinExporter.php
Thanks!

in SampleOTLPhttpExporter.php:
`$tracer = $tracerProvider->getTracer('cookbook-tracer');`

SampleZipkinExporter.php
`$tracer = $tracerProvider->getTracer("cookbook-tracer");`
