### ISSUE TITLE
110 OpenTelemetry PHP OTLP Exporter Collector doesn't show OTLP spans

### ISSUE THREAD

**Issue by erickneverson** [Aternity/Tech-Community#32]
Spans generated from OTPL Exporter do not appear to be recognized by the collector.  The opposite is true with ZipKin Exporter.

**OTLP Request**: http://localhost:8110/SampleOTLPhttpExporter.php
Response:
> Starting Sample app instrumented with OpenTelemetry, exporting OTLP http telemetry to http://aternity-opentelemetry-collector:4318/v1/traces Span: 1 Span: 2 Span: 3 Span: 4 Span: 5 Complete!

Docker output:

> ...
aternity-opentelemetry-collector-110 | 2022/07/29 22:56:58.371785, 718, WARN, appint_server.go:171, No handler for /api/appInternals/1.0/plugin found
service110_php_1                    | 172.24.0.1 - - [29/Jul/2022:22:57:00 +0000] "GET /SampleOTLPhttpExporter.php HTTP/1.1" 200 430 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
aternity-opentelemetry-collector-110 | 2022/07/29 22:57:52.006440, 718, INFO, main.go:251, In the past minute, 0 spans received and 0.00 KB of data were uploaded to Analysis Server
service110_php_1                    | 172.24.0.1 - - [29/Jul/2022:22:57:52 +0000] "-" 408 0 "-" "-"
aternity-opentelemetry-collector-110 | 2022/07/29 22:58:01.232910, 718, WARN, appint_server.go:171, No handler for /api/appInternals/1.0/plugin found
aternity-opentelemetry-collector-110 | 2022/07/29 22:58:52.007035, 718, INFO, main.go:251, In the past minute, 0 spans received and 0.00 KB of data were uploaded to Analysis Server

**ZipKin Request**: http://localhost:8110/SampleZipkinExporter.php
Response:
> Starting Sample app instrumented with OpenTelemetry, exporting Zipkin telemetry to http://aternity-opentelemetry-collector:9411/api/v2/spans Span: 1 Span: 2 Span: 3 Span: 4 Span: 5 Span: 6 Span: 7 Span: 8 Span: 9 Complete!

Docker output:

> ... 
aternity-opentelemetry-collector-110 | 2022/07/29 22:59:04.401038, 718, INFO, common.go:23, First span was received
service110_php_1                    | 172.24.0.1 - - [29/Jul/2022:22:59:00 +0000] "GET /SampleZipkinExporter.php HTTP/1.1" 200 439 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
service110_php_1                    | 172.24.0.1 - - [29/Jul/2022:22:59:51 +0000] "-" 408 0 "-" "-"
aternity-opentelemetry-collector-110 | 2022/07/29 22:59:52.007704, 718, INFO, main.go:251, In the past minute, 10 spans received and 4.25 KB of data were uploaded to Analysis Server

**Comment by gwenblum** [comment]
Actually the Aternity OpenTelemetry collector supports OTLP and Zipkin.

Maybe there was a glitch during the cookbook 110 deployment, have you tried to rebuild the cookbook (docker-compose build) ? 

On my end, it works well - i validated earlier while fixing #30 (with this change on getTracer)  both PHP samples with zipkin exporter and otlp exporter. The span are collected and stored in the Aternity SaaS Analysis Server like in this screenshot: 

![image](https://user-images.githubusercontent.com/19484478/181860874-14561f08-b895-4d5c-b8b0-1b7d2f9fb1a6.png)

**Comment by erickneverson** [comment]
I tried to rebuild on 2 separate machines but no luck.  Not sure what I'm missing.  I can't find the transactions on the Analysis server either.

**Comment by erickneverson** [comment]
Update: I can see the ZipkinExporter transactions on the Analysis server, just not the OTPL transactions.

**Comment by gwenblum** [comment]
Thanks for the update I will look closer

**Comment by gwenblum** [comment]
I finally could reproduce (i started from scratch, it worked, then stopped, restarted and got the problem) and found a workaround. Can you please have a try?

In the **docker-compose.yaml**, changing the env variable for the service110_php like this

`      OTEL_EXPORTER_OTLP_ENDPOINT: http://aternity-opentelemetry-collector:4318`

instead of

`     OTEL_EXPORTER_OTLP_ENDPOINT: http://aternity-opentelemetry-collector:4318/v1/traces`


According to the [OpenTelemetry Protocol Exporter specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md) the env var OTEL_EXPORTER_OTLP_ENDPOINT **SHOULD** contain a path.

But it appears that sometimes the opentelemetry sdk decides to append "/v1/traces" whatever the env variable contains so that when the env variable OTEL_EXPORTER_OTLP_ENDPOINT is set with a full url that contains the url path /v1/traces , the sdk will actually try to export to http://aternity-opentelemetry-collector:4318**/v1/traces/v1/traces** and will get an error.

**Comment by erickneverson** [comment]
Yes, I can see the container recognized the spans and thanks for the full explanation.  It takes a few moments for the Analysis server to show results but they finally appeared there also.

**Comment by gwenblum** [comment]
> ... It takes a few moments to show results ...

Normally it is pretty quick to ingest. If you are in search, there is a trick with the gui, after you click on of the "recent mins" buttons you can hit the range and move it to the right and the very latest ingested spans will show up in the search result.

For example it might look like:
![image](https://user-images.githubusercontent.com/19484478/181918344-d427fcb8-d5ac-407f-8ac6-dc75ed923624.png)

So you can move the range and get more recent spans:
![image](https://user-images.githubusercontent.com/19484478/181918378-494f62f2-9b8c-4cff-afff-7959a1d4292c.png)

**Comment by gwenblum** [comment]
Thanks again for raising this issue. 
I could also fix the cookbook 103 (python)
