### ISSUE TITLE
Update the links to the cookbook 001 FlyFast

### ISSUE THREAD

**Issue by gwenblum** [Aternity/Tech-Community#62]
The link to the submodule and the link 001 in the table are not pointing to the latest version of the FlyFast repo (https://github.com/Aternity/FlyFast)

**Comment by gwenblum** [comment]
@ChibiKev  can you please have look?

**Comment by ChibiKev** [comment]
Yeah. I'll create a PR for it with the updated FlyFast repo.

**Comment by ChibiKev** [comment]
Created pull request. https://github.com/Aternity/Tech-Community/pull/63
